- app/views/welcome/game_jam.html.erb
Darryl preferred this link over the root URL
> Butler logo links to BCC Interactive and 3D tech

- app/views/welcome/game_jam.html.erb
Post mortem will come at a later time.
@sethetter I still don't have a working dev environment, so you might give this a look before you deploy ;)
> announce winners and list teams, links, survey - resolves #42

- app/helpers/application_helper.rb
- app/models/event.rb
- app/views/events/index.html.erb
Only get upcoming events, wipe clean before update
Info about recurring events on Events#index
> Changes to event list page. Closes #44

- app/models/event.rb
> Sort events by time before creating

- content/mentors.md
- static/css/app.css
- static/js/mentors.js
> Mentor search

- content/mentors.md
- static/js/mentors.js
I wanted to be able to quickly clear the filter input. Added event so `esc` key does that.
> Esc clear filter

- layouts/partials/footer.html
- static/js/support.js
This PR gets data from the correct `attributes` & removes a duplicate `<script>` tag.
> Support page reporting NaN

- content/support.md
This corrects the parsing of the `## Referral Codes` header. This references issue #85.
> Wrap One Time Donations content in a div

- content/support.md
previously, the chart was in a hidden div, so it wouldn't render properly until the page was resized.
> fix chart not showing on pageload

- content/events.md
Let them speak for themselves.
> Remove blurb about recurring events

- content/events.md
- content/mentors.md
- content/support.md
- layouts/index.html
- layouts/partials/footer.html
A few small accessibility improvements per http://fontawesome.io/accessibility/.
> adding aria labels and aria-hidden attributes

- content/survey.html
- static/js/2018survey.js
Remote v local with experience included
Developer charts
> Adds more charts and graphs

- layouts/partials/head.html
Adding a meta tag to verify we own devict.org.
> Add gsuite verification meta tag

- config.toml
https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032
> Update config to work with new Hugo version

- content/about.md
> Move former board members to appropriate section of About page.

- content/meetings/2020-01-23.md
- content/meetings/2020-02-12.md
- Updated minutes for January 23rd
- Added initial minutes for February 12th
> Updating Minutes

- content/meetings/2020-01-23.md
Updated visuals of meeting notes for Janurary 23rd, 2020
> Visual Update

- content/meetings/2020-01-23.md
Two very minor typos and a clarification of @jcbwlkr 's departure.
> 2020-01-23 Minutes: minor wording/typos

- content/meetings/2020-02-12.md
Preliminary minutes for review
> Add preliminary minutes for 2020-02-12 meeting

- content/about.md
- content/support.md
> Emphasis on non-profit organisation
